CREATE TABLE IF NOT EXISTS User (
	userID INTEGER NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL,
	first_name TEXT,
	last_name TEXT,
	PRIMARY KEY("userID" AUTOINCREMENT),
	CONSTRAINT email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Movies (
	movieID INTEGER NOT NULL,
	name TEXT NOT NULL,
	rating TEXT NOT NULL,
	image TEXT,
	release_date datetime,
	description TEXT,
	PRIMARY KEY("movieID" AUTOINCREMENT)
	CONSTRAINT name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS UserAction (
	ratingID INTEGER NOT NULL,
	userID INTEGER NOT NULL,
	movieID INTEGER NOT NULL,
	userAction TEXT,
	FOREIGN KEY (userID) REFERENCES User (userID),
	FOREIGN KEY (movieID) REFERENCES Movies (movieID),
	PRIMARY KEY("ratingID" AUTOINCREMENT)
	UNIQUE(userID, movieID, userAction) ON CONFLICT REPLACE
);

CREATE TABLE IF NOT EXISTS Actor (
	actorID INTEGER NOT NULL,
	name TEXT NOT NULL,
	image TEXT NOT NULL,
	gender TEXT NOT NULL,
	dob datetime,
	history TEXT,
	PRIMARY KEY("actorID" AUTOINCREMENT)
	CONSTRAINT name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS Act (
	actID INTEGER NOT NULL,
	actorID INTEGER NOT NULL,
	movieID INTEGER NOT NULL,
	FOREIGN KEY (actorID) REFERENCES Actor (actorID),
	FOREIGN KEY (movieID) REFERENCES Movies (movieID),
	PRIMARY KEY("actID" AUTOINCREMENT)
);